"""
Clinician-facing report generation (spec Section 4).

Renders a self-contained HTML report (no external assets) with the sections the
spec requires:

1. Sample & data-quality summary
2. Current disease prediction (probability + interval)
3. Disease risk analysis
4. Future-disease forecast (if a prognostic model was supplied)
5. Model confidence & uncertainty quantification
6. Interpretability & actionable insights (top contributing taxa)

A prominent, non-negotiable medical disclaimer is always included: this is
decision-support output, not a standalone diagnosis.
"""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

DEFAULT_DISCLAIMER = (
    "This report is generated by research software for decision-support and "
    "investigational use. Microbiome-derived predictions are probabilistic "
    "inferences, not definitive diagnoses, and must be interpreted by a "
    "qualified clinician alongside other clinical findings. The only fully "
    "deterministic information here is the sequencing-derived taxonomic "
    "composition; all disease predictions carry the stated uncertainty."
)


@dataclass
class SamplePrediction:
    """All per-sample results needed to render one section of the report."""

    sample: str
    predicted_label: str
    probabilities: Dict[str, float]
    confidence: float
    proba_interval: Dict[str, Tuple[float, float]] = field(default_factory=dict)
    indeterminate: bool = False
    wellness_index: Optional[float] = None
    wellness_call: Optional[str] = None
    top_features: List[Tuple[str, float]] = field(default_factory=list)
    future_risk: Optional[Dict[str, float]] = None


@dataclass
class ReportData:
    samples: List[SamplePrediction]
    title: str = "Microbiome Disease-Prediction Report"
    qc_summary: Optional[pd.DataFrame] = None
    model_info: Dict[str, str] = field(default_factory=dict)
    reject_threshold: float = 0.9
    disclaimer: str = DEFAULT_DISCLAIMER


_CSS = """
:root { --fg:#1f2933; --muted:#616e7c; --line:#e4e7eb; --accent:#2563eb;
        --warn:#b45309; --ok:#047857; --bad:#b91c1c; }
* { box-sizing:border-box; }
body { font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
       color:var(--fg); margin:0; padding:0 0 4rem; line-height:1.5; }
header { background:#0f172a; color:#f8fafc; padding:1.5rem 2rem; }
header h1 { margin:0 0 .25rem; font-size:1.4rem; }
header .meta { color:#94a3b8; font-size:.85rem; }
main { max-width:960px; margin:0 auto; padding:0 1.5rem; }
.disclaimer { background:#fffbeb; border:1px solid #fde68a; color:#92400e;
              padding:1rem 1.25rem; border-radius:8px; margin:1.5rem 0;
              font-size:.9rem; }
.card { border:1px solid var(--line); border-radius:10px; padding:1.25rem 1.5rem;
        margin:1.25rem 0; }
.card h2 { margin:0 0 .25rem; font-size:1.1rem; }
.card h3 { font-size:1rem; color:var(--muted); margin:1rem 0 .35rem; }
.badge { display:inline-block; padding:.15rem .6rem; border-radius:999px;
         font-size:.8rem; font-weight:600; }
.badge.ok { background:#d1fae5; color:var(--ok); }
.badge.bad { background:#fee2e2; color:var(--bad); }
.badge.warn { background:#fef3c7; color:var(--warn); }
table { border-collapse:collapse; width:100%; font-size:.88rem; margin:.4rem 0; }
th,td { text-align:left; padding:.4rem .6rem; border-bottom:1px solid var(--line); }
th { color:var(--muted); font-weight:600; }
.muted { color:var(--muted); font-size:.85rem; }
.bar { height:8px; border-radius:4px; background:#e5e7eb; overflow:hidden; }
.bar > span { display:block; height:100%; background:var(--accent); }
.section-note { color:var(--muted); font-size:.82rem; margin:.2rem 0 .6rem; }
footer { max-width:960px; margin:2rem auto 0; padding:1rem 1.5rem;
         color:var(--muted); font-size:.8rem; border-top:1px solid var(--line); }
"""

# xhtml2pdf (used for PDF export) supports only a subset of CSS: no custom
# properties, flexbox or border-radius. This concrete-color stylesheet keeps the
# PDF readable (dark text on white) instead of inheriting unreadable defaults.
_CSS_PDF = """
body { font-family: Helvetica, Arial, sans-serif; color:#1f2933; font-size:10pt; }
header { color:#0f172a; }
header .meta { color:#616e7c; font-size:8pt; }
h1 { font-size:16pt; color:#0f172a; margin:0 0 4px; }
h2 { font-size:13pt; margin:0 0 2px; }
h3 { font-size:11pt; color:#616e7c; margin:10px 0 3px; }
.disclaimer { background-color:#fffbeb; border:1px solid #fde68a; color:#92400e;
              padding:8px; margin:12px 0; }
.card { border:1px solid #e4e7eb; padding:8px 10px; margin:10px 0; }
table { border-collapse:collapse; width:100%; }
th,td { border-bottom:1px solid #e4e7eb; padding:4px 6px; text-align:left; font-size:9pt; }
th { color:#616e7c; }
.badge { font-weight:bold; }
.badge.ok { color:#047857; }
.badge.bad { color:#b91c1c; }
.badge.warn { color:#b45309; }
.muted { color:#616e7c; }
.section-note { color:#616e7c; font-size:8pt; }
footer { color:#616e7c; font-size:8pt; margin-top:14px; }
"""


def _esc(value) -> str:
    return html.escape(str(value))


def _prob_bar(p: float, for_pdf: bool = False) -> str:
    pct = max(0.0, min(1.0, float(p))) * 100
    if for_pdf:
        return f"{pct:.1f}%"
    return f'<div class="bar"><span style="width:{pct:.1f}%"></span></div>'


def _badge(label: str, indeterminate: bool) -> str:
    if indeterminate:
        return f'<span class="badge warn">{_esc(label)}</span>'
    cls = "ok" if str(label).lower() in {"healthy", "control", "0"} else "bad"
    return f'<span class="badge {cls}">{_esc(label)}</span>'


def _render_sample(s: SamplePrediction, reject_threshold: float,
                   for_pdf: bool = False) -> str:
    rows = []
    for cls, p in sorted(s.probabilities.items(), key=lambda kv: -kv[1]):
        lo, hi = s.proba_interval.get(cls, (p, p))
        rows.append(
            f"<tr><td>{_esc(cls)}</td>"
            f"<td>{p:.1%}</td>"
            f"<td class='muted'>[{lo:.1%}, {hi:.1%}]</td>"
            f"<td style='width:30%'>{_prob_bar(p, for_pdf)}</td></tr>"
        )
    prob_table = (
        "<table><tr><th>Condition</th><th>Probability</th>"
        "<th>95% interval</th><th></th></tr>" + "".join(rows) + "</table>"
    )

    # Confidence / reject status
    if s.indeterminate:
        conf_note = (
            f"<p class='section-note'>Confidence {s.confidence:.1%} is below the "
            f"{reject_threshold:.0%} reporting threshold &rarr; result withheld as "
            f"<strong>INDETERMINATE</strong> (reject option).</p>"
        )
    else:
        conf_note = (
            f"<p class='section-note'>Top-class confidence: "
            f"<strong>{s.confidence:.1%}</strong> "
            f"(meets the {reject_threshold:.0%} threshold).</p>"
        )

    # Wellness
    wellness_html = ""
    if s.wellness_index is not None:
        wellness_html = (
            "<h3>Disease Risk Analysis — Wellness Index (GMWI2-style)</h3>"
            f"<p class='section-note'>Index score "
            f"<strong>{s.wellness_index:+.3f}</strong> "
            f"(positive = healthier profile) &rarr; {_badge(s.wellness_call or '—', False)}"
            "</p>"
        )

    # Future forecast
    if s.future_risk:
        fr_rows = "".join(
            f"<tr><td>{_esc(k)}</td><td>{v:.3g}</td></tr>"
            for k, v in s.future_risk.items()
        )
        future_html = (
            "<h3>Future Disease Forecast</h3>"
            "<table><tr><th>Outcome</th><th>Relative risk / score</th></tr>"
            f"{fr_rows}</table>"
        )
    else:
        future_html = (
            "<h3>Future Disease Forecast</h3>"
            "<p class='section-note'>Not available — no longitudinal/prognostic "
            "model was supplied for this run.</p>"
        )

    # Interpretability
    if s.top_features:
        feat_rows = "".join(
            f"<tr><td>{_esc(name)}</td><td>{val:+.4f}</td>"
            f"<td class='muted'>{'raises' if val >= 0 else 'lowers'} predicted risk</td></tr>"
            for name, val in s.top_features
        )
        interpret_html = (
            "<h3>Interpretability &amp; Actionable Insights</h3>"
            "<p class='section-note'>Taxa with the largest influence on this "
            "sample's prediction (occlusion/SHAP contribution to the predicted "
            "class):</p>"
            "<table><tr><th>Feature (taxon/pathway)</th><th>Contribution</th>"
            f"<th></th></tr>{feat_rows}</table>"
        )
    else:
        interpret_html = ""

    return f"""
    <section class="card">
      <h2>Sample: {_esc(s.sample)}</h2>
      <h3>Current Disease Prediction</h3>
      <p>Predicted status: {_badge(s.predicted_label, s.indeterminate)}</p>
      {prob_table}
      <h3>Model Confidence &amp; Uncertainty</h3>
      {conf_note}
      {wellness_html}
      {future_html}
      {interpret_html}
    </section>
    """


def render_html_report(report: ReportData, for_pdf: bool = False) -> str:
    """Render the full report to a single self-contained HTML string.

    Set ``for_pdf=True`` to emit a stylesheet compatible with the xhtml2pdf
    renderer (see :mod:`microbiome_predict.pdf`).
    """
    css = _CSS_PDF if for_pdf else _CSS
    generated = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    qc_html = ""
    if report.qc_summary is not None and not report.qc_summary.empty:
        qc_html = (
            '<section class="card"><h2>Sample &amp; Data Quality Summary</h2>'
            '<p class="section-note">Preprocessing read-tracking and '
            "classification rates per sample.</p>"
            + report.qc_summary.to_html(index=False, border=0)
            + "</section>"
        )

    model_rows = "".join(
        f"<tr><td>{_esc(k)}</td><td>{_esc(v)}</td></tr>"
        for k, v in report.model_info.items()
    )
    model_html = (
        '<section class="card"><h2>Model Information</h2>'
        f"<table>{model_rows}</table></section>"
        if model_rows
        else ""
    )

    samples_html = "".join(
        _render_sample(s, report.reject_threshold, for_pdf) for s in report.samples
    )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(report.title)}</title>
<style>{css}</style></head>
<body>
<header>
  <h1>{_esc(report.title)}</h1>
  <div class="meta">Generated {generated} &middot; {len(report.samples)} sample(s)
   &middot; reject threshold {report.reject_threshold:.0%}</div>
</header>
<main>
  <div class="disclaimer"><strong>Important:</strong> {_esc(report.disclaimer)}</div>
  {qc_html}
  {model_html}
  {samples_html}
</main>
<footer>
  microbiome-predict &middot; probabilistic decision-support output &middot;
  not a substitute for professional medical judgement.
</footer>
</body></html>
"""


def write_report(report: ReportData, path: str | Path) -> Path:
    """Render and write the HTML report, returning the output path."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_html_report(report), encoding="utf-8")
    return out
